<?php

declare(strict_types=1);

// AUTOGENERATED FROM config/events/taxonomy.v1.json @ version 1.0.0
// DO NOT EDIT — run `php scripts/codegen-events.php` after updating the taxonomy.

namespace App\Events\Taxonomy;

/**
 * An eligible affiliate generated a new sharing link (placement-scoped share token).
 *
 * Generated event DTO. Construct with named arguments; PHPStan will flag any
 * call site that omits a required field as an argument-count error.
 */
final readonly class AffiliateLinkShareCreated extends BaseEvent
{
    public function __construct(
        // user_id of the affiliate creating the link.
        public int $affiliate_id,
        // Opaque token attached to outbound URLs.
        public string $share_token,
        // Which placement context the share was generated from (dashboard, ebook reader, email signature).
        public string $placement_id,
    ) {}

    public static function name(): string
    {
        return 'affiliate_link_share_created';
    }

    public static function taxonomyVersion(): string
    {
        return '1.0.0';
    }
}
