<?php

declare(strict_types=1);

// AUTOGENERATED FROM config/events/taxonomy.v1.json @ version 1.0.0
// DO NOT EDIT — run `php scripts/codegen-events.php` after updating the taxonomy.

namespace App\Events\Taxonomy;

/**
 * Paid member explicitly accepted the affiliate ToS — unlocks sharing-link generation.
 *
 * Generated event DTO. Construct with named arguments; PHPStan will flag any
 * call site that omits a required field as an argument-count error.
 */
final readonly class AffiliateTermsAccepted extends BaseEvent
{
    public function __construct(
        public int $user_id,
        public string $terms_version,
        public string $accepted_ip,
    ) {}

    public static function name(): string
    {
        return 'affiliate_terms_accepted';
    }

    public static function taxonomyVersion(): string
    {
        return '1.0.0';
    }
}
