<?php

declare(strict_types=1);

// AUTOGENERATED FROM config/events/taxonomy.v1.json @ version 1.0.0
// DO NOT EDIT — run `php scripts/codegen-events.php` after updating the taxonomy.

namespace App\Events\Taxonomy;

/**
 * Visitor clicked through an affiliate sharing link. Joined to FreeAccountCreated/UpgradeCompleted via session_id for attribution.
 *
 * Generated event DTO. Construct with named arguments; PHPStan will flag any
 * call site that omits a required field as an argument-count error.
 */
final readonly class AffiliateLinkClicked extends BaseEvent
{
    public function __construct(
        public int $affiliate_id,
        public string $share_token,
        // Placement attribution captured from the link payload.
        public string $placement_id,
        public string $session_id,
        public ?string $user_agent = null,
    ) {}

    public static function name(): string
    {
        return 'affiliate_link_clicked';
    }

    public static function taxonomyVersion(): string
    {
        return '1.0.0';
    }
}
