<?php

declare(strict_types=1);

// AUTOGENERATED FROM config/events/taxonomy.v1.json @ version 1.0.0
// DO NOT EDIT — run `php scripts/codegen-events.php` after updating the taxonomy.

namespace App\Events\Taxonomy;

/**
 * Newly-created member downloaded (or re-downloaded) the lead-magnet E-Book.
 *
 * Generated event DTO. Construct with named arguments; PHPStan will flag any
 * call site that omits a required field as an argument-count error.
 */
final readonly class EbookDownloaded extends BaseEvent
{
    public function __construct(
        public int $user_id,
        public string $ebook_version,
        // in_app | email_link
        public string $delivery_channel,
    ) {}

    public static function name(): string
    {
        return 'ebook_downloaded';
    }

    public static function taxonomyVersion(): string
    {
        return '1.0.0';
    }
}
