<?php

declare(strict_types=1);

// AUTOGENERATED FROM config/events/taxonomy.v1.json @ version 1.0.0
// DO NOT EDIT — run `php scripts/codegen-events.php` after updating the taxonomy.

namespace App\Events\Taxonomy;

/**
 * Visitor loaded the free-E-Book landing page.
 *
 * Generated event DTO. Construct with named arguments; PHPStan will flag any
 * call site that omits a required field as an argument-count error.
 */
final readonly class EbookLandingViewed extends BaseEvent
{
    public function __construct(
        // Which landing-page placement variant was served (A/B test, campaign id, source page).
        public string $placement_id,
        // Anonymous session id from the visitor cookie.
        public string $session_id,
        // Affiliate user_id captured from the sharing link, if the visitor arrived via one.
        public ?int $affiliate_id = null,
        public ?string $referrer = null,
    ) {}

    public static function name(): string
    {
        return 'ebook_landing_viewed';
    }

    public static function taxonomyVersion(): string
    {
        return '1.0.0';
    }
}
