<?php

declare(strict_types=1);

// AUTOGENERATED FROM config/events/taxonomy.v1.json @ version 1.0.0
// DO NOT EDIT — run `php scripts/codegen-events.php` after updating the taxonomy.

namespace App\Events\Taxonomy;

/**
 * Visitor completed the free-account signup form. Always fires once per user.
 *
 * Generated event DTO. Construct with named arguments; PHPStan will flag any
 * call site that omits a required field as an argument-count error.
 */
final readonly class FreeAccountCreated extends BaseEvent
{
    public function __construct(
        public int $user_id,
        // Placement attribution carried from the landing page that converted the signup.
        public string $placement_id,
        // Sponsor user_id if the signup was attributed to a sharing link.
        public ?int $affiliate_id = null,
    ) {}

    public static function name(): string
    {
        return 'free_account_created';
    }

    public static function taxonomyVersion(): string
    {
        return '1.0.0';
    }
}
