<?php

declare(strict_types=1);

// AUTOGENERATED FROM config/events/taxonomy.v1.json @ version 1.0.0
// DO NOT EDIT — run `php scripts/codegen-events.php` after updating the taxonomy.

namespace App\Events\Taxonomy;

/**
 * Paid-upgrade offer was rendered to a logged-in free member.
 *
 * Generated event DTO. Construct with named arguments; PHPStan will flag any
 * call site that omits a required field as an argument-count error.
 */
final readonly class UpgradeOfferShown extends BaseEvent
{
    public function __construct(
        public int $user_id,
        // Which in-app placement showed the offer (dashboard banner, post-ebook modal, email link).
        public string $placement_id,
        public int $plan_id,
    ) {}

    public static function name(): string
    {
        return 'upgrade_offer_shown';
    }

    public static function taxonomyVersion(): string
    {
        return '1.0.0';
    }
}
