<?php

declare(strict_types=1);

// AUTOGENERATED FROM config/events/taxonomy.v1.json @ version 1.0.0
// DO NOT EDIT — run `php scripts/codegen-events.php` after updating the taxonomy.

namespace App\Events\Taxonomy;

/**
 * Member successfully purchased a paid plan. Source of truth for commission accrual triggers.
 *
 * Generated event DTO. Construct with named arguments; PHPStan will flag any
 * call site that omits a required field as an argument-count error.
 */
final readonly class UpgradeCompleted extends BaseEvent
{
    public function __construct(
        public int $user_id,
        public int $plan_id,
        public int $amount_cents,
        public string $currency,
        // Placement attribution carried from the offer that converted the purchase.
        public string $placement_id,
        // Sponsor user_id who earns the commission, if attributed.
        public ?int $affiliate_id = null,
    ) {}

    public static function name(): string
    {
        return 'upgrade_completed';
    }

    public static function taxonomyVersion(): string
    {
        return '1.0.0';
    }
}
